# Generated by Django 5.2 on 2026-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
