# Generated by Django 5.2 on 2026-09-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_basket_color_basket_size_and_more'),
        ('products', '0014_remove_product_price_productclothvariant_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basket',
            name='unique_basket_variant_per_user',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='color',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='size',
        ),
        migrations.AddField(
            model_name='basket',
            name='cloth_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productclothvariant'),
        ),
        migrations.AddField(
            model_name='basket',
            name='shoe_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productshoevariant'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'cloth_variant'), name='unique_user_cloth_variant'),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'shoe_variant'), name='unique_user_shoe_variant'),
        ),
    ]
