# Generated by Django 5.2 on 2026-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('nike', 'Nike'), ('perfect', 'Perfect')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('cloth', 'Clothe'), ('shoe', 'Shoe')], max_length=20),
        ),
    ]
