# Generated by Django 5.2 on 2026-08-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='rating',
        ),
    ]
