# Generated by Django 5.2 on 2026-08-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productcomment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
