# Generated by Django 5.2 on 2026-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productclothvariant_productshoevariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclothvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productclothvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productshoevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productshoevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
