# Generated by Django 5.2 on 2026-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productclothvariant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclothvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productclothvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productshoevariant',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productshoevariant',
            name='size',
            field=models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=20),
        ),
    ]
