# Generated by Django 5.2 on 2026-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productclothvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclothvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('black', 'Black')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productclothvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productshoevariant',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('black', 'Black')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productshoevariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
