# Generated by Django 5.2 on 2026-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productclothvariant_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='productclothvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productshoevariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productclothvariant',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='cloth_variants', to='products.color'),
        ),
        migrations.AddField(
            model_name='productshoevariant',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='shoe_variants', to='products.color'),
        ),
    ]
