# Generated by Django 5.2 on 2026-08-31 20:14

import django.db.models.deletion
from django.db import migrations, models


def clear_stale_variant_rows(apps, schema_editor):
    ProductClothVariant = apps.get_model('products', 'ProductClothVariant')
    ProductShoeVariant = apps.get_model('products', 'ProductShoeVariant')
    ProductClothVariant.objects.all().delete()
    ProductShoeVariant.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_color_remove_productclothvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclothvariant',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productshoevariant',
            name='colors',
        ),
        migrations.RunPython(clear_stale_variant_rows, migrations.RunPython.noop),
        migrations.AddField(
            model_name='productclothvariant',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloth_variants', to='products.color'),
        ),
        migrations.AddField(
            model_name='productshoevariant',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_variants', to='products.color'),
        ),
        migrations.AddConstraint(
            model_name='productclothvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_cloth_variant_combo'),
        ),
        migrations.AddConstraint(
            model_name='productshoevariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_shoe_variant_combo'),
        ),
    ]
