# Generated by Django 5.2 on 2026-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_color_product_alter_color_name_alter_color_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
