# Generated by Django 5.2 on 2026-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_color_unique_together_alter_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productclothvariant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productshoevariant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
