# Generated by Django 5.2 on 2026-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_price_productclothvariant_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='productclothvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productshoevariant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
