# Generated by Django 5.2 on 2026-09-13 19:07

import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_discount_end_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, default=products.models.default_discount_end),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
