# Generated by Django 5.2 on 2026-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_average_rating_product_rating_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_breakdown',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
