# Generated by Django 5.2 on 2026-07-10 16:39

import utils.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.accounts.models.profile_image_path),
        ),
    ]
